name: install_package
description: Install a package from local pyproject.toml
inputs:
  python_version:
    description: "Python version to install"
    default: "3.12"

runs:
  using: "composite"

  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      id: setup_python
      with:
        python-version: ${{ inputs.python_version }}
        allow-prereleases: true

    - name: Install UV
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install uv
        echo "python-version=${{ steps.setup_python.outputs.python-version }}" >> "$GITHUB_OUTPUT"

    - name: Install Dependencies
      shell: bash
      run: |
        uv sync --refresh
        echo "python-version=${{ steps.setup_python.outputs.python-version }}" >> "$GITHUB_OUTPUT"
