name: install_package
description: Install a package from local poetry
inputs:
  python_version:
    description: "Python version to install"
    default: "3.12"

runs:
  using: "composite"

  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      id: setup_python
      with:
        python-version: ${{ inputs.python_version }}
        allow-prereleases: true

    - name: Install Poetry
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        echo "python-version=${{ steps.setup_python.outputs.python-version }}" >> "$GITHUB_OUTPUT"

    - name: Setup a local virtual environment (if no poetry.toml file)
      shell: bash
      run: |
        poetry config virtualenvs.create true --local
        poetry config virtualenvs.in-project true --local

    - name: Install Dependencies
      shell: bash
      run: |
        poetry install  --no-interaction
        echo "python-version=${{ steps.setup_python.outputs.python-version }}" >> "$GITHUB_OUTPUT"
